name: 'Fetch Data to File'
description: 'Action to fetch data from a public API to a file.'
branding:
  icon: 'download'
  color: 'green'
inputs:
  url:
    description: 'url of API to fetch'
    required: true
  file: 
    description: 'location and filename'
    required: false
    default: 'actions/data.json'
outputs:
  success:
    description: 'If the data was saved'
runs:
  using: 'node12'
  main: 'index.js'